// Settings modal - schema-driven config editor across 7 sections.
// Fetches the full AppConfig via GET /api/settings, renders a schema-driven
// form (6 flat structs + the dynamic clients array), and PUTs the edited
// config back. The PUT writes config.toml and triggers a hot-reload - the
// reloader re-applies structural changes (pool, peer server, NAT, log
// filter, HTTP bind) and broadcasts config_reloaded. Running audits are
// unaffected (frozen on their startup config).

import { state } from '../state/store.js';
import { focusFirst, escHtml } from '../utils/dom-helpers.js';
import { snapshotForm, isFormDirty, addFieldError, clearFieldErrors } from '../utils/form.js';
import { request, clearPending, pendingSignal } from '../utils/net.js';
import { btnLoading, btnReset } from '../utils/buttons.js';
import { openModalEl, registerModal } from './modal.js';
import { showConfirm, CONFIRM_CANCEL } from './confirm.js';
import { clientCardHtml, expandClientCard } from './client-card.js';
import { collectOneClient, defaultClient, clientFieldId, clientDisplayName } from '../data/client-schema.js';
import { toast } from './toast.js';
import { MODE_OPTIONS, STRATEGY_OPTIONS, GOAL_DIRECTION_OPTIONS, GOAL_REACHED_ACTION_OPTIONS } from '../data/labels.js';
import { setSpeedField, setByteField, getSpeedBps } from '../utils/format.js';
import { updateGoalFieldVisibility } from './goal-form.js';

// Goal field IDs for the settings modal (set-defaults-goal_* convention,
// generated by settings_field_id). Speed-type fields have a -val suffix.
const SETTINGS_GOAL_IDS = {
  enable: 'set-defaults-goal_enabled',
  direction: 'set-defaults-goal_direction',
  uploadTargetVal: 'set-defaults-goal_upload_target-val',
  uploadTargetUnit: 'set-defaults-goal_upload_target-unit',
  downloadTargetVal: 'set-defaults-goal_download_target-val',
  downloadTargetUnit: 'set-defaults-goal_download_target-unit',
  targetSecs: 'set-defaults-goal_target_secs',
  action: 'set-defaults-goal_reached_action',
  reachedVal: 'set-defaults-goal_reached_bps-val',
  reachedUnit: 'set-defaults-goal_reached_bps-unit',
};

const SETTINGS_SECTIONS = [
  ['server', 'Server'], ['tracker', 'Tracker'], ['engine', 'Engine'],
  ['defaults', 'Defaults'], ['swarm_defaults', 'Swarm'], ['peer_server', 'Peer server'],
  ['clients', 'Clients'],
];

const SETTINGS_SCHEMA = {
  server: [
    { key: 'bind_addr', label: 'Bind address', type: 'text', hint: 'Socket address for the web UI', req: true },
    { key: 'db_url', label: 'Database URL', type: 'text', hint: 'SQLx connection string', req: true },
    { key: 'log_filter', label: 'Log filter', type: 'text', hint: 'tracing env-filter directive', req: true },
    { key: 'rebind_retry_secs', label: 'Rebind retry (s)', type: 'number', min: 1, step: 1, hint: 'Seconds to wait before retrying bind on failure', req: true },
    { key: 'sse_keepalive_secs', label: 'SSE keepalive (s)', type: 'number', min: 1, step: 1, hint: 'Interval for SSE keep-alive frames (prevents idle connection drops)', req: true },
    { key: 'timeout_secs', label: 'HTTP timeout (s)', type: 'number', min: 1, step: 1, hint: 'Tracker HTTP request timeout', req: true, cfg: 'http' },
    { key: 'max_connections', label: 'DB max connections', type: 'number', min: 1, step: 1, hint: 'SQLite connection pool size', req: true, cfg: 'database' },
    { key: 'event_log_limit', label: 'Event log limit', type: 'number', min: 1, step: 1, hint: 'Max events stored per audit', req: true, cfg: 'ui' },
    { key: 'gateway_ip', label: 'NAT gateway IP', type: 'text', hint: 'For NAT-PMP port mapping - empty = disabled', req: false, cfg: 'nat' },
    { key: 'debounce_ms', label: 'Config watcher debounce (ms)', type: 'number', min: 1, max: 10000, step: 1, hint: 'Delay before hot-reloading after config.toml changes', req: true, cfg: 'watcher' },
  ],
  tracker: [
    { key: 'peer_port', label: 'Peer port', type: 'number', min: 1, max: 65535, step: 1, hint: 'Port advertised in tracker announces', req: true },
    { key: 'default_interval_secs', label: 'Default interval (s)', type: 'number', min: 1, step: 1, hint: 'Announce interval when tracker specifies none', req: true },
    { key: 'min_interval_secs', label: 'Min interval (s)', type: 'number', min: 1, step: 1, hint: 'Minimum announce interval enforced locally', req: true },
    { key: 'max_interval_secs', label: 'Max interval (s)', type: 'number', min: 2, step: 1, hint: 'Maximum announce interval (clamps tracker values)', req: true },
  ],
  engine: [
    { key: 'tick_interval_secs', label: 'Tick interval (s)', type: 'number', min: 1, step: 1, hint: 'Core engine loop tick - drives announce scheduling', req: true },
    { key: 'stat_interval_secs', label: 'Stat interval (s)', type: 'number', min: 1, step: 1, hint: 'How often stats are computed and stored', req: true },
    { key: 'announce_jitter_pct', label: 'Announce jitter %', type: 'number', min: 0, step: 0.1, hint: 'Random jitter added to announce interval to avoid sync', req: true },
    { key: 'leech_upload_factor', label: 'Leech upload factor', type: 'number', min: 0, max: 1, step: 0.05, hint: 'Fraction of upload speed used while leeching', req: true },
    { key: 'burst_choke_probability', label: 'Burst choke probability', type: 'number', min: 0, max: 1, step: 0.05, hint: 'Chance of choking a peer each tick in burst mode', req: true },
    { key: 'stop_grace_secs', label: 'Stop grace (s)', type: 'number', min: 1, step: 1, hint: 'Grace period before force-stopping an audit', req: true },
  ],
  defaults: [
    { key: 'mode', label: 'Mode', type: 'select', options: MODE_OPTIONS, hint: 'Download+upload leeches then seeds; upload-only skips download', req: true },
    { key: 'speed_mode', label: 'Speed mode', type: 'select', options: STRATEGY_OPTIONS, hint: 'Fixed = constant speed; dynamic = adapts to swarm', req: true },
    { key: 'upload_bps', label: 'Upload (B/s)', type: 'number', min: 1, step: 1, hint: 'Upload speed in bytes per second', req: true },
    { key: 'download_bps', label: 'Download (B/s)', type: 'number', min: 1, step: 1, hint: 'Download speed in bytes per second', req: true },
    { key: 'jitter_pct', label: 'Jitter %', type: 'number', min: 0, max: 100, step: 1, hint: 'Random variation applied to speeds each tick', req: true },
    { key: 'ramp_up_secs', label: 'Ramp up (s)', type: 'number', min: 0, step: 1, hint: 'Seconds to ramp from 0 to target speed', req: true },
    { key: 'start_download_pct', label: 'Start download %', type: 'number', min: 0, max: 100, step: 1, hint: 'Initial download progress (0 = from scratch, 100 = seeder)', req: true },
    { key: 'freeze_on_zero_leechers', label: 'Freeze on zero leechers', type: 'bool', hint: 'Stop uploading when no leechers are present', req: true },
    { key: 'freeze_on_zero_seeders', label: 'Freeze on zero seeders', type: 'bool', hint: 'Stop downloading when no seeders are present', req: true },
    { key: 'goal_enabled', label: 'Goal enabled', type: 'bool', hint: 'Track a target amount; with a deadline the engine adjusts speed to hit it', req: true },
    { key: 'goal_direction', label: 'Goal direction', type: 'select', options: GOAL_DIRECTION_OPTIONS, hint: 'Which counter grows toward the target', req: true },
    { key: 'goal_upload_target', label: 'Goal upload target', type: 'amount', hint: 'Upload bytes to reach (upload / download+upload)', req: true },
    { key: 'goal_download_target', label: 'Goal download target', type: 'amount', hint: 'Download bytes to reach (download / download+upload)', req: true },
    { key: 'goal_target_secs', label: 'Goal time (s)', type: 'number', min: 0, max: 31536600, step: 1, hint: 'Deadline from start; 0 = ETA-only (no speed adjustment)', req: true },
    { key: 'goal_reached_action', label: 'On goal reached', type: 'select', options: GOAL_REACHED_ACTION_OPTIONS, hint: 'Stop the task, continue at the initial speed, or switch to a custom speed', req: true },
    { key: 'goal_reached_bps', label: 'Reached speed', type: 'speed', hint: 'Custom speed after the goal is reached (continue_custom only); 0 = freeze', req: true },
  ],
  swarm_defaults: [
    { key: 'avg_leecher_download_bps', label: 'Avg leecher download (B/s)', type: 'number', min: 1, step: 1, hint: 'Estimated average download speed of real leechers', req: true },
    { key: 'seed_share_factor', label: 'Seed share factor', type: 'number', min: 0.01, max: 1, step: 0.01, hint: 'Fraction of swarm upload allocated to us', req: true },
    { key: 'fair_share_multiplier', label: 'Fair share multiplier', type: 'number', min: 0, step: 0.1, hint: 'Multiplier for fair-share bandwidth allocation', req: true },
    { key: 'max_upload_bps', label: 'Max upload (B/s)', type: 'number', min: 0, step: 1, hint: '0 = unlimited', req: true },
    { key: 'max_download_bps', label: 'Max download (B/s)', type: 'number', min: 0, step: 1, hint: '0 = unlimited', req: true },
  ],
  peer_server: [
    { key: 'enabled', label: 'Enabled', type: 'bool', hint: 'Accept incoming peer-wire connections', req: true },
    { key: 'max_connections', label: 'Max connections', type: 'number', min: 1, step: 1, hint: 'Global limit on concurrent peer connections', req: true },
    { key: 'max_per_ip', label: 'Max per IP', type: 'number', min: 1, step: 1, hint: 'Limit on connections from a single IP address', req: true },
    { key: 'handshake_timeout_secs', label: 'Handshake timeout (s)', type: 'number', min: 1, step: 1, hint: 'Drop peer if handshake not received within this time', req: true },
    { key: 'write_timeout_secs', label: 'Write timeout (s)', type: 'number', min: 1, step: 1, hint: 'Drop peer if a write takes longer than this', req: true },
    { key: 'idle_timeout_secs', label: 'Idle timeout (s)', type: 'number', min: 1, step: 1, hint: 'Drop peer if no messages received for this long', req: true },
    { key: 'body_read_timeout_secs', label: 'Body read timeout (s)', type: 'number', min: 1, step: 1, hint: 'Timeout for reading a peer message body', req: true },
    { key: 'accept_error_backoff_ms', label: 'Accept error backoff (ms)', type: 'number', min: 0, step: 1, hint: 'Pause before retrying accept after an error', req: true },
    { key: 'capture_keepalive_secs', label: 'Capture keepalive (s)', type: 'number', min: 1, step: 1, hint: 'Keepalive interval advertised during fingerprint capture', req: true },
  ],
};

function settingsFieldId(section, key) { return 'set-' + section + '-' + key; }

export function renderSettingsClients() {
  const container = document.getElementById('settings-clients');
  if (!container || !state.settingsConfig) return;
  container.innerHTML = state.settingsConfig.clients.map(function (c, i) { return clientCardHtml(i, c); }).join('');
}

export function populateSettingsFields() {
  for (const [section] of SETTINGS_SECTIONS) {
    if (section === 'clients') continue;
    for (const f of SETTINGS_SCHEMA[section]) {
      const id = settingsFieldId(section, f.key);
      const cfgSection = f.cfg || section;
      const v = state.settingsConfig[cfgSection][f.key];
      if (f.type === 'bool') {
        const el = document.getElementById(id);
        if (el) el.checked = !!v;
      } else if (f.type === 'speed') {
        setSpeedField(id + '-val', id + '-unit', v ?? 0);
      } else if (f.type === 'amount') {
        setByteField(id + '-val', id + '-unit', v ?? 0);
      } else {
        const el = document.getElementById(id);
        if (el) el.value = v;
      }
    }
  }
}

export function switchSettingsSection(section) {
  state.settingsActiveSection = section;
  document.querySelectorAll('#settings-nav button').forEach(function (b) {
    b.classList.toggle('active', b.dataset.section === section);
  });
  document.querySelectorAll('.settings-pane').forEach(function (p) {
    p.classList.toggle('active', p.dataset.section === section);
  });
}

function collectSettingsClients() {
  const clients = [];
  document.querySelectorAll('.client-card').forEach(function (card) {
    if (card.dataset.idx === 'cap') return; // skip capture-modal card
    const c = collectOneClient(card.dataset.idx);
    if (c) clients.push(c);
  });
  return clients;
}

function collectSettings() {
  const cfg = state.settingsConfig;
  for (const [section] of SETTINGS_SECTIONS) {
    if (section === 'clients') continue;
    for (const f of SETTINGS_SCHEMA[section]) {
      const id = settingsFieldId(section, f.key);
      const cfgSection = f.cfg || section;
      if (f.type === 'bool') {
        const el = document.getElementById(id);
        if (el) cfg[cfgSection][f.key] = el.checked;
      } else if (f.type === 'speed' || f.type === 'amount') {
        cfg[cfgSection][f.key] = getSpeedBps(id + '-val', id + '-unit');
      } else if (f.type === 'number') {
        const el = document.getElementById(id);
        if (el) cfg[cfgSection][f.key] = el.value === '' ? 0 : Number(el.value);
      } else {
        const el = document.getElementById(id);
        if (el) cfg[cfgSection][f.key] = el.value;
      }
    }
  }
  cfg.clients = collectSettingsClients();
  return cfg;
}

export function addSettingsClient() {
  if (!state.settingsModalOpen) return;
  state.settingsConfig.clients = collectSettingsClients();
  state.settingsConfig.clients.unshift(defaultClient());
  renderSettingsClients();
  // Expand the newly added card (index 0) and switch to Clients section
  switchSettingsSection('clients');
  const card = document.querySelector('.client-card[data-idx="0"]');
  if (card) {
    expandClientCard(card);
    const firstInput = card.querySelector('input, textarea, select');
    if (firstInput) firstInput.focus();
  }
  updateSaveButton();
}

export async function removeSettingsClient(idx) {
  if (!state.settingsModalOpen) return;
  // Collect current form state to get the client name for the prompt
  const clients = collectSettingsClients();
  const client = clients[idx];
  if (!client) return;
  const name = client.label ? clientDisplayName(client) : 'New client';
  const confirmed = await showConfirm(
    'Remove client',
    'Remove <strong>' + escHtml(name) + '</strong>? This cannot be undone.',
    [CONFIRM_CANCEL, { label: 'Remove', class: 'btn-danger', value: 'ok' }]
  );
  if (confirmed !== 'ok') return;
  state.settingsConfig.clients = collectSettingsClients();
  state.settingsConfig.clients.splice(idx, 1);
  renderSettingsClients();
  updateSaveButton();
}

export function openSettingsModal() {
  const sm = document.getElementById('settings-modal');
  openModalEl(sm, closeSettingsModal);
  state.settingsModalOpen = true;
  populateSettingsFields();
  renderSettingsClients();
  updateSettingsGoalVisibility();
  switchSettingsSection('server');
  const sc = document.getElementById('settings-content');
  state.settingsFormSnapshot = snapshotForm(sc);
  updateSaveButton();
  focusFirst(sm);
}

// Shared visibility driver - delegates to goal-form.js with the settings
// field IDs. Uses hideAllWhenDisabled (settings modal hides each sub-field's
// parent .field div when the goal is unchecked). Re-exported so init.js
// can call it from the change listener.
export function updateSettingsGoalVisibility() {
    updateGoalFieldVisibility(SETTINGS_GOAL_IDS, { hideAllWhenDisabled: true, timeAsPicker: false });
}

export function settingsIsDirty() {
  return isFormDirty(document.getElementById('settings-content'), state.settingsFormSnapshot);
}

export function updateSaveButton() {
  const btn = document.getElementById('save-settings-btn');
  if (!btn) return;
  btn.disabled = !settingsIsDirty();
}

// Reset settings modal state after the overlay is closed. Keeps
// state.settingsConfig cached - SSE config_reloaded keeps it fresh, so
// reopening is instant (no re-fetch). Only clears modal-specific state.
function resetSettingsModal() {
  state.settingsModalOpen = false;
  state.settingsFormSnapshot = '';
  state.settingsActiveSection = 'server';
  clearSettingsErrors();
  document.getElementById('settings-clients').innerHTML = '';
  const btn = document.getElementById('save-settings-btn');
  if (btn) { btnReset(btn); btn.textContent = 'Save'; }
  clearPending('save-settings');
}

export const closeSettingsModal = registerModal({ isDirty: settingsIsDirty, noun: 'changes', reset: resetSettingsModal });

export function saveSettings(btn) {
  if (!state.settingsModalOpen) return;
  btnLoading(btn);
  const cfg = collectSettings();
  state.settingsSaveAt = Date.now();
  const signal = pendingSignal('save-settings');
  request('/api/settings', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(cfg),
    signal,
  }).then(function (r) {
    if (!r.ok) {
      showSettingsErrors(r.text);
      toast('Validation failed - see highlighted fields', 'error');
      btnReset(btn);
      state.settingsSaveAt = 0;
      updateSaveButton();
      return;
    }
    clearSettingsErrors();
    state.settingsFormSnapshot = '';
    toast('Settings saved', 'success');
    closeSettingsModal();
  });
}

// Parse a backend validation error string and highlight the offending fields.
// Backend errors look like "clients[].label must not be empty (client `...`)"
// or "peer_server.max_connections must be >= 1".
function showSettingsErrors(errMsg) {
  clearSettingsErrors();
  // Try to match "clients[].<field>" with optional client name in backticks
  const clientMatch = errMsg.match(/clients\[\]\.(\w+).*client `([^`]+)`/);
  if (clientMatch) {
    const field = clientMatch[1];
    const clientName = clientMatch[2];
    // Find the client card matching the name
    const cards = document.querySelectorAll('.client-card');
    for (let i = 0; i < cards.length; i++) {
      const p = clientFieldId(i, '');
      const labelEl = document.getElementById(p + 'label');
      const versionEl = document.getElementById(p + 'version');
      if (labelEl && versionEl) {
        const name = clientDisplayName({ label: labelEl.value, version: versionEl.value, peer_id_prefix: document.getElementById(p + 'peer_id_prefix').value });
        if (name === clientName) {
          const fieldEl = document.getElementById(p + field);
          if (fieldEl) {
            addFieldError(fieldEl.closest('.field'), errMsg);
          }
          expandClientCard(cards[i]);
          return;
        }
      }
    }
  }
  // Generic section.field error - try to highlight in settings panes
  const sectionMatch = errMsg.match(/^(\w+)\.(\w+)/);
  if (sectionMatch) {
    const section = sectionMatch[1];
    const key = sectionMatch[2];
    const el = document.getElementById(settingsFieldId(section, key)) || document.getElementById(settingsFieldId('server', key));
    if (el) {
      addFieldError(el.closest('.field'), errMsg);
    }
    return;
  }
  // Fallback: just show the toast
  toast(errMsg, 'error');
}

function clearSettingsErrors() {
  clearFieldErrors(document);
}
